# Generated by Django 3.1.1 on 2020-09-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_remove_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Navbar', 'Navbar'), ('Landing', 'Landing'), ('About', 'About'), ('Projects/Services', 'Projects/Services'), ('Social', 'Social')], default='Navbar', max_length=200)),
                ('jsId', models.IntegerField()),
                ('category', models.ManyToManyField(to='category.Category')),
            ],
        ),
    ]
