# Generated by Django 3.1.1 on 2020-12-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.CharField(choices=[('Navbar', 'Navbar'), ('Landing', 'Landing'), ('About', 'About'), ('Projects', 'Projects'), ('Social', 'Social')], default='Navbar', max_length=200),
        ),
    ]
