# Generated by Django 2.2.1 on 2020-09-04 15:46

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=jsonfield.fields.JSONField(),
        ),
    ]
