# Generated by Django 3.1.1 on 2020-09-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20200905_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='landing',
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
    ]
