# Generated by Django 3.1.1 on 2020-09-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_website_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='aboutpage',
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='project',
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
    ]
