# Generated by Django 3.1.1 on 2020-09-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_auto_20200919_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='navbar',
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
    ]
