# Generated by Django 3.1.1 on 2020-12-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_auto_20200920_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='color',
            field=models.CharField(default='#5f27cd', max_length=200),
        ),
    ]
