# Generated by Django 3.1.1 on 2020-12-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_auto_20201213_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='social',
            field=models.JSONField(blank=True, default='', max_length=200, null=True),
        ),
    ]
